"""initial schema

Revision ID: 93c8afc5b912
Revises: 
Create Date: 2026-07-22 21:12:46.606244
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = '93c8afc5b912'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_defs',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_phase', sa.String(length=50), nullable=False),
    sa.Column('phase_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('input_snapshot_ref', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_defs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_table('artefacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('artefact_type', sa.String(length=100), nullable=False),
    sa.Column('stable_key', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artefacts_project_id'), 'artefacts', ['project_id'], unique=False)
    op.create_table('artefact_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artefact_id', sa.String(length=36), nullable=False),
    sa.Column('version_label', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefacts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artefact_versions_artefact_id'), 'artefact_versions', ['artefact_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artefact_version_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artefact_version_id'], ['artefact_versions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_artefact_version_id'), 'reviews', ['artefact_version_id'], unique=False)
    op.create_table('review_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity_ref', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_review_id'), 'review_comments', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_comments_review_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_reviews_artefact_version_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_artefact_versions_artefact_id'), table_name='artefact_versions')
    op.drop_table('artefact_versions')
    op.drop_index(op.f('ix_artefacts_project_id'), table_name='artefacts')
    op.drop_table('artefacts')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('agent_defs')
    # ### end Alembic commands ###
